name: Update Astronauts Data

on:
  push:
    branches:
      - main  # Or 'master' if that’s the default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can set this to your preferred Node version

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: npm install

      # Step 4: List files in the repo (for debugging, to ensure the path is correct)
      - name: List files
        run: |
          echo "Listing files in the repository"
          ls -R

      # Step 5: Run the script to update astronaut data
      - name: Run update-astronauts.js
        run: node update-astronauts.js

      # Step 6: Commit and push the updated astronauts.json back to the repo
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add astronauts.json
          git commit -m "Updated astronauts data"
          git push
