name: Update Astronauts Data

on:
  schedule:
    - cron: '0 * * * *'  # This runs the action every hour

jobs:
  update-astronauts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run update script
      run: node update_astronauts.js

    - name: Commit and push astronauts.json
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add astronauts.json
        git commit -m "Update astronauts data"
        git push
